//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingVaccineClient.ProcedurService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProcedurService.IProcedurService")]
    public interface IProcedurService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcedurService/GetVaccines", ReplyAction="http://tempuri.org/IProcedurService/GetVaccinesResponse")]
        TrackingVaccineService.Vaccine[] GetVaccines();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcedurService/GetVaccines", ReplyAction="http://tempuri.org/IProcedurService/GetVaccinesResponse")]
        System.Threading.Tasks.Task<TrackingVaccineService.Vaccine[]> GetVaccinesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcedurService/GetVaccine", ReplyAction="http://tempuri.org/IProcedurService/GetVaccineResponse")]
        TrackingVaccineService.Vaccine GetVaccine(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcedurService/GetVaccine", ReplyAction="http://tempuri.org/IProcedurService/GetVaccineResponse")]
        System.Threading.Tasks.Task<TrackingVaccineService.Vaccine> GetVaccineAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcedurService/create", ReplyAction="http://tempuri.org/IProcedurService/createResponse")]
        bool create(TrackingVaccineService.Vaccine vaccine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcedurService/create", ReplyAction="http://tempuri.org/IProcedurService/createResponse")]
        System.Threading.Tasks.Task<bool> createAsync(TrackingVaccineService.Vaccine vaccine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcedurService/update", ReplyAction="http://tempuri.org/IProcedurService/updateResponse")]
        bool update(TrackingVaccineService.Vaccine vaccine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcedurService/update", ReplyAction="http://tempuri.org/IProcedurService/updateResponse")]
        System.Threading.Tasks.Task<bool> updateAsync(TrackingVaccineService.Vaccine vaccine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcedurService/delete", ReplyAction="http://tempuri.org/IProcedurService/deleteResponse")]
        bool delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcedurService/delete", ReplyAction="http://tempuri.org/IProcedurService/deleteResponse")]
        System.Threading.Tasks.Task<bool> deleteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProcedurServiceChannel : TrackingVaccineClient.ProcedurService.IProcedurService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcedurServiceClient : System.ServiceModel.ClientBase<TrackingVaccineClient.ProcedurService.IProcedurService>, TrackingVaccineClient.ProcedurService.IProcedurService {
        
        public ProcedurServiceClient() {
        }
        
        public ProcedurServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcedurServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcedurServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcedurServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TrackingVaccineService.Vaccine[] GetVaccines() {
            return base.Channel.GetVaccines();
        }
        
        public System.Threading.Tasks.Task<TrackingVaccineService.Vaccine[]> GetVaccinesAsync() {
            return base.Channel.GetVaccinesAsync();
        }
        
        public TrackingVaccineService.Vaccine GetVaccine(int id) {
            return base.Channel.GetVaccine(id);
        }
        
        public System.Threading.Tasks.Task<TrackingVaccineService.Vaccine> GetVaccineAsync(int id) {
            return base.Channel.GetVaccineAsync(id);
        }
        
        public bool create(TrackingVaccineService.Vaccine vaccine) {
            return base.Channel.create(vaccine);
        }
        
        public System.Threading.Tasks.Task<bool> createAsync(TrackingVaccineService.Vaccine vaccine) {
            return base.Channel.createAsync(vaccine);
        }
        
        public bool update(TrackingVaccineService.Vaccine vaccine) {
            return base.Channel.update(vaccine);
        }
        
        public System.Threading.Tasks.Task<bool> updateAsync(TrackingVaccineService.Vaccine vaccine) {
            return base.Channel.updateAsync(vaccine);
        }
        
        public bool delete(int id) {
            return base.Channel.delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> deleteAsync(int id) {
            return base.Channel.deleteAsync(id);
        }
    }
}
